# typed: false
# frozen_string_literal: true

# Generated by bin/update-formula — do not edit by hand.
class AgentLock < Formula
  desc "Advisory locks for the coding agents that share one checkout"
  homepage "https://github.com/kigster/agent-lock"
  url "https://rubygems.org/downloads/agent-lock-0.1.0.gem"
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"
  license "MIT"

  # Its own Ruby, rather than the system one. macOS ships 2.6, the gem needs
  # 3.2 or newer, and installing into the system Ruby would want sudo.
  depends_on "ruby"

  resource "dry-cli" do
    url "https://rubygems.org/downloads/dry-cli-1.4.1.gem"
    sha256 "b8015bb76c708aa8705a36faf694973e75eeeffca39b89c8e172dc6f66a7d874"
  end

  def install
    ENV["GEM_HOME"] = libexec

    resources.each do |dependency|
      dependency.verify_download_integrity(dependency.fetch)
      system "gem", "install", dependency.cached_download, "--no-document", "--ignore-dependencies"
    end

    system "gem", "install", cached_download, "--no-document", "--ignore-dependencies"

    # Both names, since `alo` is the one anybody types twice.
    %w[agent-lock alo].each do |program|
      (bin/program).write_env_script libexec/"bin/#{program}", GEM_HOME: ENV["GEM_HOME"]
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/agent-lock version")

    system "git", "init", "-q", "-b", "main", testpath
    (testpath/"lib").mkpath
    (testpath/"lib/thing.rb").write("# stub\n")

    with_env(AGENT_ID: "brew-test") do
      assert_match "ACQUIRED lib/**", shell_output("#{bin}/alo acquire lib 'brew test' --dir #{testpath}")
      assert_match "YOURS lib/**", shell_output("#{bin}/alo check lib/thing.rb --dir #{testpath}")
      assert_match "RELEASED lib/**", shell_output("#{bin}/alo release lib --dir #{testpath}")
    end

    # A lock the tap did not take must read as free, and exit 0.
    with_env(AGENT_ID: "brew-test-other") do
      assert_match "FREE", shell_output("#{bin}/alo check lib --dir #{testpath}")
    end
  end
end
