# typed: false
# frozen_string_literal: true

# Generated by .github/workflows/update-formula.yml — do not edit by hand.
class Sopsy < Formula
  desc "The missing developer experience for SOPS"
  homepage "https://github.com/kigster/sopsy"
  version "1.3.0"
  license "MIT"

  depends_on "age"
  depends_on "sops"

  on_macos do
    depends_on "age-plugin-se"

    on_arm do
      url "https://github.com/kigster/sopsy/releases/download/v1.3.0/sopsy-aarch64-apple-darwin.tar.gz"
      sha256 "b98f57abca7ddd3bf68dda9477df9535fb038fda7142272d8bc47a82e113f8eb"
    end
    on_intel do
      url "https://github.com/kigster/sopsy/releases/download/v1.3.0/sopsy-x86_64-apple-darwin.tar.gz"
      sha256 "a6d7aff4418f1f6c907cf1fa66d114202aaa4f28af0887d73dcd41c4b4f6806c"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kigster/sopsy/releases/download/v1.3.0/sopsy-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "43aab955f291d30e1dd6830c726067d66f6e33646f6348da1d3303f19e9089d4"
    end
    on_intel do
      url "https://github.com/kigster/sopsy/releases/download/v1.3.0/sopsy-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "992c453fec32acf72f154994402f5873f0436d74dcf9d16c19b62178e5bb1ce2"
    end
  end

  def install
    bin.install "sopsy"
    generate_completions_from_executable(bin/"sopsy", "completion")
  end

  test do
    assert_match "sopsy #{version}", shell_output("#{bin}/sopsy --version")
  end
end
