# typed: false
# frozen_string_literal: true

# Generated by .github/workflows/update-formula.yml — do not edit by hand.
class Sopsy < Formula
  desc "The missing developer experience for SOPS"
  homepage "https://github.com/kigster/sopsy"
  version "1.1.0"
  license "MIT"

  depends_on "age"
  depends_on "sops"

  on_macos do
    depends_on "age-plugin-se"

    on_arm do
      url "https://github.com/kigster/sopsy/releases/download/v1.1.0/sopsy-aarch64-apple-darwin.tar.gz"
      sha256 "c1ace50a54cfa321d1d0329dfed679f05f56bcc66668410678b4f6adc1a1c058"
    end
    on_intel do
      url "https://github.com/kigster/sopsy/releases/download/v1.1.0/sopsy-x86_64-apple-darwin.tar.gz"
      sha256 "867975a856d91eb6648af96e319c91427548ad5cc2ca7d1f85e46ac5cab2293d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kigster/sopsy/releases/download/v1.1.0/sopsy-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "cb8b8a5a48ce02e9eb2ebfce7012915b86dab0ee24832fb052d2b60ff36dbe7d"
    end
    on_intel do
      url "https://github.com/kigster/sopsy/releases/download/v1.1.0/sopsy-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "9397f2a0c0693191914d3a2338727aeb0db746a43ea3a0bf1312036de9219706"
    end
  end

  def install
    bin.install "sopsy"
    generate_completions_from_executable(bin/"sopsy", "completion")
  end

  test do
    assert_match "sopsy #{version}", shell_output("#{bin}/sopsy --version")
  end
end
