# typed: false
# frozen_string_literal: true

# Generated by .github/workflows/update-formula.yml — do not edit by hand.
class Sopsy < Formula
  desc "The missing developer experience for SOPS"
  homepage "https://github.com/kigster/sopsy"
  version "1.1.2"
  license "MIT"

  depends_on "age"
  depends_on "sops"

  on_macos do
    depends_on "age-plugin-se"

    on_arm do
      url "https://github.com/kigster/sopsy/releases/download/v1.1.2/sopsy-aarch64-apple-darwin.tar.gz"
      sha256 "e83bfc83ffa9ade2ce01538e60afe4d25891ee6c33ffb992da76e245863015dd"
    end
    on_intel do
      url "https://github.com/kigster/sopsy/releases/download/v1.1.2/sopsy-x86_64-apple-darwin.tar.gz"
      sha256 "1995a65a49262b325eebc31bb5cfb49850bcdf02f3387f21aa5bdc6b7e4bb948"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/kigster/sopsy/releases/download/v1.1.2/sopsy-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "857fd84edc20f6b5ad5bf018681780f09191679d3e1337319b595a48aeaeccc3"
    end
    on_intel do
      url "https://github.com/kigster/sopsy/releases/download/v1.1.2/sopsy-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5124d0d3f5c6b53aa04f8e780351e853028f05352b1dd20e0a2fab74405524c6"
    end
  end

  def install
    bin.install "sopsy"
    generate_completions_from_executable(bin/"sopsy", "completion")
  end

  test do
    assert_match "sopsy #{version}", shell_output("#{bin}/sopsy --version")
  end
end
