# typed: false
# frozen_string_literal: true

# Generated by .github/workflows/update-svg2og.yml — do not edit by hand.
class Svg2og < Formula
  desc "Convert Mermaid SVG exports for clean import into OmniGraffle"
  homepage "https://github.com/kigster/svg2og"
  version "0.1.0"
  license "MIT"

  depends_on :macos

  on_macos do
    on_arm do
      url "https://github.com/kigster/svg2og/releases/download/v0.1.0/svg2og-aarch64-apple-darwin.tar.gz"
      sha256 "273ac3ba42bf1b5d887980a50ff059a1a28997f2c1b63c753db70fed2c71c232"
    end
    on_intel do
      url "https://github.com/kigster/svg2og/releases/download/v0.1.0/svg2og-x86_64-apple-darwin.tar.gz"
      sha256 "eb1d36ec1af6fbde9b9fb51b30f73418d1b46a36cdbbede28aa6c3475dfe1b99"
    end
  end

  def install
    bin.install "svg2og"
  end

  test do
    assert_match "svg2og #{version}", shell_output("#{bin}/svg2og --version")
  end
end
